---
- name: minikube server deployment
  hosts: 192.168.1.34
  become: true
  remote_user: kmaster
  tasks:
    - name: Delete Kubernetes resource
      command: kubectl delete -f /home/kmaster/project-php/apache.yaml
      become_user: kmaster
    - name: create Kubernetes resource
      command: kubectl create -f /home/kmaster/project-php/apache.yaml
      become_user: kmaster

