apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app-deploy
  template:
    metadata:
      labels:
        app: php-app-deploy
    spec:
      containers:
      - name: php
        image: msy061618/k8-project-php:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-app-deploy # sepc selector label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004 
  type: NodePort
